#!/bin/sh
printf 'Updating homebrew...'
brew update
printf ' done\n'

printf 'Upgrading formulae...'
brew upgrade
printf ' done\n'

printf 'Upgrading casks...'
brew cask upgrade --greedy
printf ' done\n'

printf "Deleting old formulae..."
brew cleanup

printf "Checking system..."
brew doctor
printf ' done\n'

