#!/bin/sh

blue=$(tput setaf 153)
bold=$(tput bold)
normal=$(tput sgr0)

function info() {
  printf "${blue}${bold}$1${normal}\n"
}

info 'Updating homebrew...'
brew update
info 'done'

info 'Upgrading formulae...'
brew upgrade
info 'done'

info 'Upgrading casks...'
brew upgrade --cask
info 'done'

info 'Deleting old formulae...'
brew cleanup
info 'done'

info 'Checking system...'
brew doctor
info 'done'
